language: bash
sudo: required
script:
# bootstrap the minimal environment required to run upv
- upv/github-travis/upv_bootstrap_travis.sh
# pull images to speed-up the build
- ./upv.sh --pull
# download
- ./upv.sh pipenv "run dpp run ./download"
# build
- ./upv.sh upv/static-files-build build
# deploy
- ./upv.sh upv/github-travis-static-deployment deploy
