language: bash
sudo: required
script:
#.upv--label=install_docker
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
#--.upv
- ./pull.sh
- ./upv.sh . dpp "run ./download" && ./upv.sh . build
- >
  [ "${TRAVIS_PULL_REQUEST}" != "false" ] ||\
  [ "${TRAVIS_BRANCH}" != "master" ] ||\
  echo "${TRAVIS_COMMIT_MESSAGE}" | grep -- "--no-deploy" >/dev/null ||\
  (./upv.sh . deploy && echo "updated site should be available at http://orihoch.uumpa.com/calendar-web-app/dist/")
